### PR TITLE
fix: Refactor code for testability and add tests

### LINKED ISSUE #11: As a visitor, I can create an account
- Guide: https://codevoweb.com/golang-gorm-postgresql-user-registration-with-refresh-tokens/ 
- Guide: https://codevoweb.com/golang-and-gorm-user-registration-email-verification/

- Guide: https://webera.blog/implement-refresh-token-with-jwt-in-react-app-using-axios-1910087c3d7

#### Needs:

- #10

### PR DESCRIPTION
**Pull request by alexstojda**
Merge blocked by #15 

- fix(backend): Honour c.Abort() in middleware
- fix(backend): Add tests for auth package
- fix(backend): Add tests for errors and user packages
- fix(backend): Report test coverage to sonarcloud

closes #11

### CODE REVIEW

File: internal/app/api/user/user_suite_test.go [hunk 1]
```diff
@@ -0,0 +1,236 @@
+package user_test
```
Comment (philippelorange) [inline internal/app/api/user/user_suite_test.go:1]: should this file be with the user.go file in models?

File: internal/utils/gormlogger_test.go [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+			gormLogger.Info(ctx, "an %s", "error")
+			m.Expect(b.String()).To(m.MatchRegexp("^{\"level\":\"info\".*"))
+		})
+	})
+
+	g.When("Trace is called", func() {
+		g.It("should run", func() {
+			t := time.Now()
+			gormLogger.Trace(ctx, t, func() (string, int64) {
+				return "SELECT * FROM users", 69
```
Comment (philippelorange) [inline internal/utils/gormlogger_test.go:62]: nice

**Review by philippelorange — APPROVED** [review]

File: internal/app/api/user/user_suite_test.go (hunk 1 above)
Comment (alexstojda) [reply internal/app/api/user/user_suite_test.go:1]: Negative, the models directory will just contain the structs that define shared types and database tables.
